[package]
name = "fungible_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = '_'
initial_creator_addr = "_"

[dev-addresses]
launchpad_addr = "0x123" 
initial_creator_addr = "0x990"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
